### ISSUE TITLE
Text flickering in preferences with addon enabled on tab change

### ISSUE THREAD

**Issue by Fracture64** [zebus3d/ExtraInfo#4]
**Blender Version**
Broken: version: 2.80 (sub 75), branch: master, commit date: 2019-07-29 14:47, hash: `rBf6cb5f54494e`

**System Information**
Operating system: Windows-10-10.0.18362 64 Bits
Graphics card: GeForce GTX 1060 6GB/PCIe/SSE2 NVIDIA Corporation 4.5.0 NVIDIA 430.39

**Short description of error**
Pressing any of tabs on left causes text in top button change style

**Exact steps for others to reproduce the error**
1 Enable addon
2 Press any of tab buttons on left
3 Observe change in text drawing of top button:
![image](https://user-images.githubusercontent.com/48379181/64777650-1bbffb80-d574-11e9-9e88-c8a22bd7949f.png)

4 Note what moving mouse outside of button what was pressed will cause top button text to redraw normally

**Comment by zebus3d** [comment]
Now this is solved in 0.0.8.
Thanks.
