### ISSUE TITLE
Flickering drop shadow on simple viewport axis

### ISSUE THREAD

**Issue by Fracture64** [zebus3d/ExtraInfo#5]
**Blender Version**
Broken: version: 2.80 (sub 75), branch: master, commit date: 2019-07-29 14:47, hash: `rBf6cb5f54494e`

**System Information**
Operating system: Windows-10-10.0.18362 64 Bits
Graphics card: GeForce GTX 1060 6GB/PCIe/SSE2 NVIDIA Corporation 4.5.0 NVIDIA 430.39

**Short description of error**
Addon adds drop shadow to viewport axis:
![image](https://user-images.githubusercontent.com/48379181/64779644-fd5bff00-d577-11e9-8b20-d70fea7570fc.png)

**Exact steps for others to reproduce the error**
1 Activate addon
2 Change 3D Viewport Axis to Simple Axis. Note what issue is not present with Interactive Navigation option
3 Observe flickering shadow. It appears and sometimes disappears on viewport orbiting with middle mouse and switching between perspective / orthographic modes

**Comment by zebus3d** [comment]
now this is solved in 0.0.8.
